# Generated by Django 3.2.7 on 2021-11-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('mailing_address', models.TextField(blank=True)),
                ('physical_address', models.TextField(blank=True)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('subscription_until', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='USA', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='USD', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Seller', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'job_title',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('bank_details', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'managers',
            },
        ),
        migrations.CreateModel(
            name='StaffSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Indeed', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'staff_source',
            },
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=300)),
                ('body', models.TextField(default='')),
                ('language', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('responsible_manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backoffice.manager')),
            ],
            options={
                'verbose_name_plural': 'TemplateEmail',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('currency', models.CharField(blank=True, default='EUR', max_length=4)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('bonus', models.PositiveIntegerField(blank=True, default=0)),
                ('comment', models.TextField(blank=True)),
                ('job_title', models.ManyToManyField(blank=True, to='backoffice.JobTitle')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.staffsource')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.staffstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='RUB', max_length=4)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('tariff', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('responsible_manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backoffice.manager')),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Interview', max_length=300)),
                ('meeting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(blank=True, default='mit.jit.si', max_length=300)),
                ('applicants', models.ManyToManyField(to='backoffice.Staff')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.company')),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.quiz')),
                ('responsible_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Training', max_length=250)),
                ('body', models.TextField(default='')),
                ('files', models.FileField(blank=True, null=True, upload_to='courses_files/')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('job_title', models.ManyToManyField(blank=True, to='backoffice.JobTitle')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.manager'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.subscription'),
        ),
    ]
