# Generated by Django 3.2.7 on 2021-12-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('applied_for', models.CharField(choices=[('HR', 'HR'), ('STAFF', 'STAFF'), ('APPLICANT', 'APPLICANT')], max_length=50)),
                ('number_of_questions', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.quiz'),
        ),
    ]
