# Generated by Django 3.2.7 on 2022-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('archive', 'archive'), ('template', 'template')], default='template', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(default='c6e7d8d2a5', max_length=300),
        ),
    ]
