# Generated by Django 3.2.7 on 2021-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20211206_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateemail',
            name='receivers',
            field=models.ManyToManyField(blank=True, to='backoffice.Staff'),
        ),
    ]
