# Generated by Django 3.2.7 on 2022-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20221203_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(default='b96ae32162', max_length=300),
        ),
    ]
