# Generated by Django 3.2.7 on 2021-12-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_templateemail_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateemail',
            name='responsible_manager',
        ),
    ]
