# Generated by Django 3.2.7 on 2022-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20221203_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='template',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(default='5d69eb0fe9', max_length=300),
        ),
    ]
