# Generated by Django 3.2.7 on 2022-12-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20221208_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(default='ca0af40921', max_length=300),
        ),
    ]
