# Generated by Django 3.2.7 on 2021-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_rename_templateemail_emailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('template', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'EmailTemaplates',
            },
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name_plural': 'EmailMessage'},
        ),
    ]
