# Generated by Django 3.2.7 on 2021-12-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20211208_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name_plural': 'EmailMessages'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name_plural': 'EmailTemplates'},
        ),
    ]
