# Generated by Django 3.2.7 on 2021-12-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='GuaranteeHR', max_length=500)),
                ('body', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
