# Generated by Django 3.2.7 on 2021-11-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20211117_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_correct',
        ),
        migrations.CreateModel(
            name='Marks_Of_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
    ]
