# Generated by Django 3.2.7 on 2021-12-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20211206_1223'),
        ('survey', '0005_auto_20211206_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_of_user',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.quiz'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
